#!/usr/bin/env python3

import os
import sys
import requests
import json
import time
import statistics 
import numpy
import threading

# Import ./utils.py
import utils

class vaultClient():

    def __init__(self):
      addr = os.environ.get('VAULT_ADDR')
      token = os.environ.get('VAULT_TOKEN')

      if not addr:
        utils.logging.error('Environment variable VAULT_ADDR not found. Exiting')
        exit(1)
      
      if not token:
        utils.logging.error('Environment variable VAULT_TOKEN not found. Exiting')
        exit(1)

      self.addr = addr
      self.token = token
      self.headers = {'X-Vault-Token': self.token}

  
def transitEncrypt(vaultClient, mount):

  apiMethod = '/v1/' + mount + '/encrypt/'
  encryptionKey = 'application-1'
  data = utils.generateCreditCardNumbers(5)

  for i in data:
    payload = {'plaintext': i}
    url = vaultClient.addr + apiMethod + encryptionKey

    response = requests.post(url=url, data=json.dumps(payload), headers=vaultClient.headers)
    responseJson = response.json() 
    responseTimes.append(response.elapsed.total_seconds())
    responseCodes.append(response.status_code)

    utils.logging.debug(responseJson['data']['ciphertext'])

if __name__ == "__main__":
  
    # Parse args and start logging
    args = utils.argParser().parse_args(sys.argv[1:])
    utils.startLogging(args.verbosity)

    # Init Vault client
    client = vaultClient()

    # Mount transit secrets engine at path
    transitPath = args.path
    utils.createMount(client, transitPath, 'transit')
 
    # Create a global variable to collect stats from each thread 
    global responseTimes
    global responseCodes
    responseTimes = []
    responseCodes = []

    # Set test arguments
    numberOfThreads = args.threads 

    # Run test for the duration set my cli args, this is approx at best
    timeEnd = time.time() + args.duration

    while time.time() < timeEnd:

        # Start threading workload
        threads = []
    
        # Create a list of each thread
        for i in range(numberOfThreads):
          threadNumber = i
          t = threading.Thread(target=transitEncrypt, args=(client, transitPath))
          t.daemon = True
          threads.append(t)
    
        # Start each thread
        for i in range(numberOfThreads):
          threads[i-1].start()
    
        # Add each thread to the thread pool
        for i in range(numberOfThreads):
          threads[i-1].join()
  
    # Sleep to allow all requests to finish
    time.sleep(1)

    # Calculate statistics
    numberOfRequests = len(responseTimes)
    numberOf200 = responseCodes.count(200)
    meanResponseTime = round(statistics.mean(responseTimes), 5)
    percentile90 = round(numpy.percentile(responseTimes, 90), 5)
    percentile95 = round(numpy.percentile(responseTimes, 95), 5)
    percentile99 = round(numpy.percentile(responseTimes, 99), 5)
    requestsPerSecond = numberOfRequests / args.duration
    
    # Output statistics
    print(f'Requests per second {requestsPerSecond}')
    print(f'Number of Reqests {numberOfRequests}')
    print(f'Number of 200s {numberOf200}')
    print(f'Mean = {meanResponseTime} seconds')
    print(f'90%  = {percentile90} seconds')
    print(f'95%  = {percentile95} seconds')
    print(f'99%  = {percentile99} seconds')
